server:
  port: 8000
spring:
  application:
    name: microservice-provider-user
  jpa:
    properties:
      hibernate:
        default_schema: schema

  datasource:                           # 指定数据源
    url: jdbc:sqlserver://172.20.13.25:1433;DatabaseName=Crawler
    data-username: sa
    data-password: qu90()op
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

logging:                                # 配置日志级别，让hibernate打印出执行的SQL
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:
    prefer-ip-address: true